// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, pass, username) VALUES ($1, $2, $3)
RETURNING id, email, username
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Pass     string `json:"pass"`
	Username string `json:"username"`
}

type CreateUserRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	Username string      `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Pass, arg.Username)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.Username)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const editUser = `-- name: EditUser :one
UPDATE users SET
email = COALESCE(NULLIF($2, ''), email),
username = COALESCE(NULLIF($3, ''), username)
WHERE id = $1
RETURNING id, email, username
`

type EditUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Email    interface{} `json:"email"`
	Username interface{} `json:"username"`
}

type EditUserRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	Username string      `json:"username"`
}

func (q *Queries) EditUser(ctx context.Context, arg EditUserParams) (EditUserRow, error) {
	row := q.db.QueryRow(ctx, editUser, arg.ID, arg.Email, arg.Username)
	var i EditUserRow
	err := row.Scan(&i.ID, &i.Email, &i.Username)
	return i, err
}

const editUserPass = `-- name: EditUserPass :one
UPDATE users SET
pass = $2
WHERE id = $1
RETURNING id, email, username
`

type EditUserPassParams struct {
	ID   pgtype.UUID `json:"id"`
	Pass string      `json:"pass"`
}

type EditUserPassRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	Username string      `json:"username"`
}

func (q *Queries) EditUserPass(ctx context.Context, arg EditUserPassParams) (EditUserPassRow, error) {
	row := q.db.QueryRow(ctx, editUserPass, arg.ID, arg.Pass)
	var i EditUserPassRow
	err := row.Scan(&i.ID, &i.Email, &i.Username)
	return i, err
}

const getAuthCredentialsByEmail = `-- name: GetAuthCredentialsByEmail :one
SELECT id, is_admin, pass FROM users WHERE email = $1
`

type GetAuthCredentialsByEmailRow struct {
	ID      pgtype.UUID `json:"id"`
	IsAdmin bool        `json:"is_admin"`
	Pass    string      `json:"pass"`
}

func (q *Queries) GetAuthCredentialsByEmail(ctx context.Context, email string) (GetAuthCredentialsByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAuthCredentialsByEmail, email)
	var i GetAuthCredentialsByEmailRow
	err := row.Scan(&i.ID, &i.IsAdmin, &i.Pass)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	Username string      `json:"username"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.Username)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, username FROM users ORDER BY id
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	Username string      `json:"username"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
